accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='account_signup'),
    path('login/', views.LoginView.as_view(), name='account_signin'),
    path('logout/', views.LogoutView, name='account_logout'),
    path('mypage/', views.MypageView.as_view(), name='account_mypage'),
    path('favorite/', views.FavoriteView.as_view(), name='account_favorite'),
]

app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

onenaviDev/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('sale.urls')),
    path('', include('balance.urls')),
    path('', include('menu.urls')),
    path('', include('clinic.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import UserManager, PermissionsMixin
from django.utils import timezone

class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
  prefectures = [ 
    ("北海道"  ,"北海道"  ),  
    ("青森県"  ,"青森県"  ),  
    ("岩手県"  ,"岩手県"  ),  
    ("宮城県"  ,"宮城県"  ),  
    ("秋田県"  ,"秋田県"  ),  
    ("山形県"  ,"山形県"  ),  
    ("福島県"  ,"福島県"  ),  
    ("茨城県"  ,"茨城県"  ),  
    ("栃木県"  ,"栃木県"  ),  
    ("群馬県"  ,"群馬県"  ),  
    ("埼玉県"  ,"埼玉県"  ),  
    ("千葉県"  ,"千葉県"  ),  
    ("東京都"  ,"東京都"  ),  
    ("神奈川県","神奈川県"),
    ("新潟県"  ,"新潟県"  ),  
    ("富山県"  ,"富山県"  ),  
    ("石川県"  ,"石川県"  ),  
    ("福井県"  ,"福井県"  ),  
    ("山梨県"  ,"山梨県"  ),  
    ("長野県"  ,"長野県"  ),  
    ("岐阜県"  ,"岐阜県"  ),  
    ("静岡県"  ,"静岡県"  ),  
    ("愛知県"  ,"愛知県"  ),  
    ("三重県"  ,"三重県"  ),  
    ("滋賀県"  ,"滋賀県"  ),  
    ("京都府"  ,"京都府"  ),  
    ("大阪府"  ,"大阪府"  ),  
    ("兵庫県"  ,"兵庫県"  ),  
    ("奈良県"  ,"奈良県"  ),  
    ("和歌山県","和歌山県"),
    ("鳥取県"  ,"鳥取県"  ),  
    ("島根県"  ,"島根県"  ),  
    ("岡山県"  ,"岡山県"  ),  
    ("広島県"  ,"広島県"  ),  
    ("山口県"  ,"山口県"  ),  
    ("徳島県"  ,"徳島県"  ),  
    ("香川県"  ,"香川県"  ),  
    ("愛媛県"  ,"愛媛県"  ),  
    ("高知県"  ,"高知県"  ),  
    ("福岡県"  ,"福岡県"  ),  
    ("佐賀県"  ,"佐賀県"  ),  
    ("長崎県"  ,"長崎県"  ),  
    ("熊本県"  ,"熊本県"  ),  
    ("大分県"  ,"大分県"  ),  
    ("宮崎県"  ,"宮崎県"  ),  
    ("鹿児島県","鹿児島県"),
    ("沖縄県"  ,"沖縄県"  ),  
  ]
  email = models.EmailField('メールアドレス', unique=True)
  nickname = models.CharField(("ニックネーム"), max_length=30, blank=True)
  address = models.CharField(("居住地"), choices=prefectures, max_length=4, blank=True)

  is_staff = models.BooleanField(
      ('staff status'),
      default=False,
      help_text=('Designates whether the user can log into this admin site.'),
  )
  is_active = models.BooleanField(
      ('active'),
      default=True,
      help_text=(
          'Designates whether this user should be treated as active. '
          'Unselect this instead of deleting accounts.'
      ),
  )

  objects = UserManager()
  USERNAME_FIELD = 'email'
  EMAIL_FIELD = 'email'
  REQUIRED_FIELDS = []

  class Meta:
      verbose_name = ('user')
      verbose_name_plural = ('users')

  def clean(self):
      super().clean()
      self.email = self.__class__.objects.normalize_email(self.email)

accounts/forms.py
from django import forms
from allauth.account.forms import SignupForm

class SignupUserForm(SignupForm):
  nickname = forms.CharField(max_length=30)

  def save(self, request):
    user = super(SignupUserForm, self).save(request)
    user.nickname = self.cleaned_data['nickname']
    user.save()
    return user

accounts/views.py
from django.views import View
from accounts.models import CustomUser
from django.shortcuts import render, redirect
from allauth.account import views
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from urllib import request
from django.contrib.auth import login,logout
from accounts.forms import SignupUserForm
from sale.models import SaleItem, SaleFavorite

class LoginView(views.LoginView):
  template_name = 'accounts/signin.html'

class MypageView(LoginRequiredMixin,View):
  def get(self, request, *args, **kwargs):
    user_data = CustomUser.objects.get(id=request.user.id)
    return render(request, 'accounts/mypage.html', {
      'user_data': user_data,
    })

class FavoriteView(LoginRequiredMixin,View):
  def get(self, request, *args, **kwargs):
    user_data = CustomUser.objects.get(id=request.user.id)
    item_data = SaleItem.objects.all()
    favorite_list = []
    shop = []
    for data in item_data:
      favorite = data.salefavorite_set.filter(user=request.user)
      if favorite.exists():
        favorite_list.append(data)
    
    params = {
      'user_data': user_data,
      'favorite_list': favorite_list
    }
    return render(request, 'accounts/favorite.html', params)

class SignupView(views.SignupView):
  template_name = 'accounts/signup.html'
  form_class = SignupUserForm

def LogoutView(request):
    logout(request)
    return redirect('account_signin')

app/templates/accounts/favorite.html
{% extends "app/base.html" %}

{% block fontawesome %}
<script src="https://kit.fontawesome.com/75f3d7c9c9.js" crossorigin="anonymous"></script>
{% endblock  %}

{% block content %}

<div class="mb-10">
  <p class="text-xl">お気に入り</p>
</div>
<div>
  <div>
    <p class="pl-3 relative text-xl border-b pb-4 mb-4 before:absolute before:w-1 before:h-7 before:left-0 before:top-0 before:bg-emerald-700">特売商品</p>
    <div class="grid grid-cols-4 gap-y-7 gap-x-4 mb-8">
      {% for item_data in favorite_list %}
        {% if forloop.counter <= 4 %}
          <div>
            <div
              class="relative h-[275px] mb-3.5 bg-gray-50 rounded-md flex justify-center place-items-center shadow-sm"
            >
              <img
                class="h-auto w-40 mix-blend-multiply"
                src={{ item_data.url }}
                alt=""
              />
              <div>
                <form action="{% url 'sale_favorite' %}" method="post">
                  {% csrf_token %}
                  {% if favorite_list %}
                  <button class="absolute right-3 top-2" type="button" id="ajax_sale_favorite" name="{{ item_data.id }}">
                    <i class="fa-solid fa-heart text-red-600 text-lg"></i>
                  </button>
                  {% else %}
                  <button class="absolute right-3 top-2" type="button" id="ajax_sale_favorite" name="{{ item_data.id }}">
                    <i class="fa-regular fa-heart text-lg"></i>
                  </button>
                  {% endif %}
                </form>
              </div>
            </div>
            <div class="mb-1">
              <p class="text-xs text-gray-500">{{ item_data.shop }}</p>
            </div>
            <div class="mb-2">
              <p class="w-[275px] text-sm leading-5 overflow-hidden h-10">
                {{ item_data.name }}
              </p>
            </div>
            <div class="flex items-center">
              <div>
                <p class="text-xl">¥{{ item_data.price }}</p>
              </div>
              <div class="ml-auto">
              </div>
            </div>
          </div>
        {% endif %}
      {% endfor %}
    </div>
  </div>
  <div>
    <p class="pl-3 relative text-xl border-b pb-4 mb-4 before:absolute before:w-1 before:h-7 before:left-0 before:top-0 before:bg-emerald-700">病院一覧</p>
  </div>
</div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  $(document).ready(function(event){
      $(document).on('click', '#ajax_sale_favorite', function(event){
          event.preventDefault();
          $.ajax({
              type: 'POST',
              url: "{% url 'sale_favorite' %}",
              data: {
                  'item_id': $(this).attr('name'),
                  'csrfmiddlewaretoken': '{{ csrf_token }}'},
              dataType: 'json',
              success: function(response){
                  selector = document.getElementsByName(response.item_id);
                  if(response.favorited){
                      $(selector).html("<i class='fa-solid fa-heart text-red-600 text-lg'></i>");
                  }
                  else {
                      $(selector).html("<i class='fa-regular fa-heart text-lg'></i>");
                  }
              }
          });
      });
  });
</script>
{% endblock %}

app/templates/accounts/mypage.html
{% extends "app/base.html" %}

{% block content %}

<div class="mb-10">
  <p class="text-xl">マイページ</p>
</div>

{% endblock %}

app/templates/accounts/signin.html
{% extends "app/base_signin.html" %}

{% load widget_tweaks %} 

{% block content %}

<div class="my-12 w-[350px] mx-auto grid place-items-center">
  <h1 class="text-3xl text-center mb-5 tracking-widest" style="font-family: Montserrat;">SIGN IN</h1>
  <div class="mb-8 text-red-600 text-sm"></div>
  <div class="w-full">
    <form method="post">
      {% csrf_token %}
      <div class="mb-4">
        <label for="id_login" class="text-xs mb-2">メールアドレス</label>
        {% render_field form.login class="block py-1 px-2 h-9 bg-white text-sm w-full border-b focus:outline-none focus:border-emerald-700" placeholder="" autocomplete="off" %}
      </div>
      <div class="mb-2">
        <label for="id_password" class="text-xs mb-2">パスワード</label>
        {% render_field form.password class="block py-1 px-2 h-9 bg-white text-sm w-full border-b focus:outline-none focus:border-emerald-700" placeholder="" autocomplete="off" %}
      </div>
      <div class="mb-12 text-right">
        <a href="" class="text-gray-400 text-xs underline">パスワードをお忘れの方</a>
      </div>
      <div class="grid place-items-center mb-10">
        <button class="w-2/3 h-12 border border-emerald-700 text-emerald-700 rounded hover:bg-emerald-700 hover:text-white text-sm transition" type="submit">サインイン</button>
      </div>
      <div class="text-center">
        <a href="{% url 'account_signup' %}" class="text-sm underline">初めてご利用の方は、新規登録へお進みください。</a>
      </div>
    </form>
  </div>
</div>

{% endblock %}

app/templates/accounts/signup.html
{% extends "app/base_signin.html" %}

{% load widget_tweaks %} 

{% block content %}

<div class="my-12 w-[350px] mx-auto grid place-items-center">
  <h1 class="text-3xl text-center mb-5 tracking-widest" style="font-family: Montserrat;">SIGN UP</h1>
  <div class="mb-8 text-red-600 text-sm"></div>
  <div class="w-full">
    <form method="post">
      {% csrf_token %}
      <div class="mb-4">
        <label for="id_nickname" class="text-xs mb-2">ユーザー名<span class="text-red-600 text-sm">*</span></label>
        {% render_field form.nickname class="block py-1 px-2 h-9 bg-white text-sm w-full border-b focus:outline-none focus:border-emerald-700" placeholder="" autocomplete="off" %}
      </div>
      <div class="mb-4">
        <label for="id_email" class="text-xs mb-2">メールアドレス<span class="text-red-600 text-sm">*</span></label>
        {% render_field form.email class="block py-1 px-2 h-9 bg-white text-sm w-full border-b focus:outline-none focus:border-emerald-700" placeholder="" autocomplete="off" %}
      </div>
      <div class="mb-4">
        <label for="id_password1" class="text-xs mb-2">パスワード<span class="text-red-600 text-sm">*</span></label>
        {% render_field form.password1 class="block py-1 px-2 h-9 bg-white text-sm w-full border-b focus:outline-none focus:border-emerald-700" placeholder="" autocomplete="off" %}
      </div>
      <div class="mb-12">
        <label for="id_password2" class="text-xs mb-2">パスワード(確認用)<span class="text-red-600 text-sm">*</span></label>
        {% render_field form.password2 class="block py-1 px-2 h-9 bg-white text-sm w-full border-b focus:outline-none focus:border-emerald-700" placeholder="" autocomplete="off" %}
      </div>
      <div class="grid place-items-center mb-10">
        <button class="w-2/3 h-12 border border-emerald-700 text-emerald-700 rounded hover:bg-emerald-700 hover:text-white text-sm transition" type="submit">サインアップ</button>
      </div>
      <div class="text-center">
        <p class="text-sm">アカウントをお持ちですか？<a href="{% url 'account_signin' %}" class="text-sm underline">サインインはこちら</a></p>
      </div>
    </form>
  </div>
</div>

{% endblock %}